import type {Clip,Keyframe,Project,Track} from '../types/editor';
const uid=()=>Math.random().toString(36).slice(2,10);
const mapClips=(p:Project,fn:(c:Clip,t:Track)=>Clip|null):Project=>({...p,tracks:p.tracks.map(t=>({...t,clips:t.clips.flatMap(c=>{const next=fn(c,t);return next?[next]:[]})}))});
export function addClip(project:Project,trackId:string,clip:Omit<Clip,'id'|'trackId'>):Project{return {...project,tracks:project.tracks.map(t=>t.id===trackId?{...t,clips:[...t.clips,{...clip,id:uid(),trackId}]}:t),updatedAt:new Date().toISOString()};}
export function trimClip(project:Project,clipId:string,sourceIn:number,sourceOut:number):Project{if(sourceOut<=sourceIn)throw new Error('Trim out must be greater than in');return mapClips(project,c=>c.id===clipId?{...c,sourceIn,sourceOut,duration:(sourceOut-sourceIn)/c.speed}:c);}
export function splitClip(project:Project,clipId:string,time:number):Project{return {...project,tracks:project.tracks.map(t=>({...t,clips:t.clips.flatMap(c=>{if(c.id!==clipId)return [c]; if(time<=c.start||time>=c.start+c.duration)throw new Error('Split time must be inside clip'); const leftDur=time-c.start; const rightDur=c.duration-leftDur; return [{...c,duration:leftDur,sourceOut:c.sourceIn+leftDur*c.speed},{...c,id:uid(),start:time,duration:rightDur,sourceIn:c.sourceIn+leftDur*c.speed}];})}))};}
export const moveClip=(p:Project,clipId:string,start:number,trackId?:string)=>({...p,tracks:p.tracks.map(t=>({...t,clips:t.clips.map(c=>c.id===clipId?{...c,start,trackId:trackId??c.trackId}:c)}))});
export const duplicateClip=(p:Project,clipId:string)=>({...p,tracks:p.tracks.map(t=>({...t,clips:t.clips.flatMap(c=>c.id===clipId?[c,{...c,id:uid(),start:c.start+c.duration}]:[c])}))});
export const deleteClip=(p:Project,clipId:string)=>mapClips(p,c=>c.id===clipId?null:c);
export const setSpeed=(p:Project,clipId:string,speed:number)=>{if(speed<0.1||speed>4)throw new Error('Speed must be between 0.1x and 4x');return mapClips(p,c=>c.id===clipId?{...c,speed,duration:(c.sourceOut-c.sourceIn)/speed}:c);};
export const addKeyframe=(p:Project,clipId:string,k:Omit<Keyframe,'id'>)=>mapClips(p,c=>c.id===clipId?{...c,keyframes:[...c.keyframes,{...k,id:uid()}].sort((a,b)=>a.time-b.time)}:c);
