export type Plan='free'|'pro'|'ultra';
export type TrackType='video'|'audio'|'text'|'overlay'|'effect';
export type ClipType='video'|'photo'|'audio'|'text'|'effect';
export type ExportResolution='480p'|'720p'|'1080p'|'2k'|'4k';
export interface Keyframe<T=number>{id:string;time:number;property:string;value:T;easing:'linear'|'easeIn'|'easeOut'|'easeInOut'}
export interface Clip{id:string;type:ClipType;uri?:string;trackId:string;start:number;duration:number;sourceIn:number;sourceOut:number;speed:number;volume:number;opacity:number;position:{x:number;y:number};scale:number;rotation:number;filter?:string;effectIds:string[];keyframes:Keyframe[];text?:TextLayer;chromaKey?:ChromaKey;mask?:Mask;blendMode?:'normal'|'screen'|'multiply'|'overlay'}
export interface TextLayer{value:string;fontFamily:string;fontSize:number;bold:boolean;italic:boolean;align:'left'|'center'|'right';color:string;opacity:number;animation?:'fade'|'slide'|'zoom'|'pop'|'typewriter'}
export interface ChromaKey{color:string;strength:number;tolerance:number;edge:number;shadow:number;spillReduction:number}
export interface Mask{shape:'rectangle'|'circle'|'linear'|'gradient'|'custom';feather:number;opacity:number;position:{x:number;y:number};scale:number;rotation:number}
export interface Track{id:string;type:TrackType;name:string;clips:Clip[];muted?:boolean;locked?:boolean}
export interface Project{id:string;userId:string;name:string;tracks:Track[];duration:number;fps:24|30|60;updatedAt:string;thumbnailUrl?:string}
export interface ExportSettings{resolution:ExportResolution;fps:24|30|60;quality:'low'|'medium'|'high'|'maximum';format:'mp4'}
